{% set name = "intake-dataframe-catalog" %}
{% set version = "0.4.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/intake_dataframe_catalog-{{ version }}.tar.gz
  sha256: 1a3b001d9904f71262d93b10dc5f95aad635c6e1a2175760a37b84e726451b4e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0.0
    - versioneer
    - pip
  run:
    - itables
    - polars >=1.12
    - fsspec
    - numpy
    - pyyaml
    - toolz
    - python >={{ python_min }}
    - intake >=0.7.0
    - pandas

test:
  imports:
    - intake_dataframe_catalog
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ACCESS-NRI/intake-dataframe-catalog
  summary: An intake driver for a searchable table of intake sources and associated metadata
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
