{% set name = "intake-dataframe-catalog" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/intake_dataframe_catalog-{{ version }}.tar.gz
  sha256: 209f1099675adaa174baa027f8d8627730fee30f7413e032722be7263377f2bd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0.0
    - versioneer
    - pip
  run:
    - fsspec
    - numpy
    - pyyaml
    - toolz
    - python >={{ python_min }}
    - intake >=0.7.0
    - pandas

test:
  imports:
    - intake_dataframe_catalog
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ACCESS-NRI/intake-dataframe-catalog
  summary: An intake driver for a searchable table of intake sources and associated metadata
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
