{% set name = "intake-dataframe-catalog" %}
{% set version = "0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/intake_dataframe_catalog-{{ version }}.tar.gz
  sha256: b9b30b85b6fac5b0588812687b90aa1b533726562f50349ee99b494c27deb52a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=61.0.0
    - versioneer
    - pip
  run:
    - python >=3.9
    - intake <2.0.0
    - pandas

test:
  imports:
    - intake_dataframe_catalog
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ACCESS-NRI/intake-dataframe-catalog
  summary: An intake driver for a searchable table of intake sources and associated metadata
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
